language: cpp

dist: bionic 

matrix:
  include:
    - name: "Linux" # system
      os: linux  # betriebssystem, wo es laufen soll
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
      addons:
        apt:
          sources:
            - 'ubuntu-toolchain-r-test'
          packages:
            - g++-7
            - lcov
            - gcovr
    - name: "MacOS"
            os: osx
            osx_image: xcode10
            env:
              - MATRIX_EVAL="CC=clang && CXX=clang++"
# vor instalieren erst mal checken, ob matrix_eval true ist(benötigte compiler instaliert ist)
before_install:
  eval "${MATRIX_EVAL}"

install:
  - mkdir build
  - cd build 
  - pip install --user conan
  - source ~/.profile
  - conan user
  - conan install .. # benötige pkt instalieren (eine ordner zurück)